<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ranni Tewfik Data Analysis Portfolio - CDC Data Exercise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Ranni Tewfik Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html" rel="" target="">
 <span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/products/report/starter-analysis-report.html" rel="" target="">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../coding-exercise/coding-exercise.html" rel="" target="">
 <span class="dropdown-text">R Coding Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html" rel="" target="">
 <span class="dropdown-text">Data Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html" rel="" target="">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidytuesday-exercise/tidytuesday-exercise.html" rel="" target="">
 <span class="dropdown-text">Tidy Tuesday Exercise</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rtewfik/rannitewfik-MADA-portfolio" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CDC Data Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="part-1---about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="part-1---about-the-data">Part 1 - About the Data</h2>
<p>The “NCHS - Leading Causes of Death: United States” dataset used for this exercise provides data on the age-adjusted death rates for the 10 leading causes of death in the U.S. (1999-2017). The source is the mortality data from the National Vital Statistics System (CDC/NCHS).</p>
<p>Resident death certificates from all 50 states and D.C. were used to collect the data on demographic and medical characteristics. Age-adjusted death rates (per 100,000 population) are based on the 2000 U.S. standard population. Populations used for computing death rates after 2010 are postcensal estimates based on the 2010 census.</p>
<p>The dataset has 10,868 observations and six variables: year, X113 cause name (specific cause of death), cause name (categorical cause of death), state, deaths, and age-adjusted death rate. To learn more about the data, please visit the <a href="https://data.cdc.gov/NCHS/NCHS-Leading-Causes-of-Death-United-States/bi63-dtpu/about_data">CDC</a> website.</p>
</section>
<section id="part-2---processing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="part-2---processing-the-data">Part 2 - Processing the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load the required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Load the raw data</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>cdc_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"NCHS_Leading_Causes_of_Death.csv"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Get an overview and summary of the raw data</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cdc_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10868 obs. of  6 variables:
 $ Year                   : int  2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 ...
 $ X113.Cause.Name        : chr  "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" "Accidents (unintentional injuries) (V01-X59,Y85-Y86)" ...
 $ Cause_Name             : chr  "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" ...
 $ State                  : chr  "United States" "Alabama" "Alaska" "Arizona" ...
 $ Deaths                 : int  169936 2703 436 4184 1625 13840 3037 2078 608 427 ...
 $ Age_Adjusted_Death_Rate: num  49.4 53.8 63.7 56.2 51.8 33.2 53.6 53.2 61.9 61 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year      X113.Cause.Name     Cause_Name           State          
 Min.   :1999   Length:10868       Length:10868       Length:10868      
 1st Qu.:2003   Class :character   Class :character   Class :character  
 Median :2008   Mode  :character   Mode  :character   Mode  :character  
 Mean   :2008                                                           
 3rd Qu.:2013                                                           
 Max.   :2017                                                           
     Deaths        Age_Adjusted_Death_Rate
 Min.   :     21   Min.   :   2.6         
 1st Qu.:    612   1st Qu.:  19.2         
 Median :   1718   Median :  35.9         
 Mean   :  15460   Mean   : 127.6         
 3rd Qu.:   5756   3rd Qu.: 151.7         
 Max.   :2813503   Max.   :1087.3         </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for weird symbols or missing values in all six variables</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cdc_raw<span class="sc">$</span>Year, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
 572  572  572  572  572  572  572  572  572  572  572  572  572  572  572  572 
2015 2016 2017 &lt;NA&gt; 
 572  572  572    0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cdc_raw<span class="sc">$</span>X113.Cause.Name, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                 Accidents (unintentional injuries) (V01-X59,Y85-Y86) 
                                                                  988 
                                                           All Causes 
                                                                  988 
                                            Alzheimer's disease (G30) 
                                                                  988 
                                   Cerebrovascular diseases (I60-I69) 
                                                                  988 
                         Chronic lower respiratory diseases (J40-J47) 
                                                                  988 
                                          Diabetes mellitus (E10-E14) 
                                                                  988 
                          Diseases of heart (I00-I09,I11,I13,I20-I51) 
                                                                  988 
                                    Influenza and pneumonia (J09-J18) 
                                                                  988 
                 Intentional self-harm (suicide) (*U03,X60-X84,Y87.0) 
                                                                  988 
                                        Malignant neoplasms (C00-C97) 
                                                                  988 
Nephritis, nephrotic syndrome and nephrosis (N00-N07,N17-N19,N25-N27) 
                                                                  988 
                                                                 &lt;NA&gt; 
                                                                    0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cdc_raw<span class="sc">$</span>Cause_Name, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             All causes     Alzheimer's disease                  Cancer 
                    988                     988                     988 
                   CLRD                Diabetes           Heart disease 
                    988                     988                     988 
Influenza and pneumonia          Kidney disease                  Stroke 
                    988                     988                     988 
                Suicide  Unintentional injuries                    &lt;NA&gt; 
                    988                     988                       0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cdc_raw<span class="sc">$</span>State, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             Alabama               Alaska              Arizona 
                 209                  209                  209 
            Arkansas           California             Colorado 
                 209                  209                  209 
         Connecticut             Delaware District of Columbia 
                 209                  209                  209 
             Florida              Georgia               Hawaii 
                 209                  209                  209 
               Idaho             Illinois              Indiana 
                 209                  209                  209 
                Iowa               Kansas             Kentucky 
                 209                  209                  209 
           Louisiana                Maine             Maryland 
                 209                  209                  209 
       Massachusetts             Michigan            Minnesota 
                 209                  209                  209 
         Mississippi             Missouri              Montana 
                 209                  209                  209 
            Nebraska               Nevada        New Hampshire 
                 209                  209                  209 
          New Jersey           New Mexico             New York 
                 209                  209                  209 
      North Carolina         North Dakota                 Ohio 
                 209                  209                  209 
            Oklahoma               Oregon         Pennsylvania 
                 209                  209                  209 
        Rhode Island       South Carolina         South Dakota 
                 209                  209                  209 
           Tennessee                Texas        United States 
                 209                  209                  209 
                Utah              Vermont             Virginia 
                 209                  209                  209 
          Washington        West Virginia            Wisconsin 
                 209                  209                  209 
             Wyoming                 &lt;NA&gt; 
                 209                    0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_raw<span class="sc">$</span>Deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     21     612    1718   15460    5756 2813503 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc_raw<span class="sc">$</span>Age_Adjusted_Death_Rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    2.6    19.2    35.9   127.6   151.7  1087.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Drop the "X113.Cause.Name" variable for the processed data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>cdc <span class="ot">&lt;-</span> <span class="fu">select</span>(cdc_raw, <span class="sc">-</span>X113.Cause.Name)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(cdc)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Get an overview and summary of the processed data</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(cdc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10868 obs. of  5 variables:
 $ Year                   : int  2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 ...
 $ Cause_Name             : chr  "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" "Unintentional injuries" ...
 $ State                  : chr  "United States" "Alabama" "Alaska" "Arizona" ...
 $ Deaths                 : int  169936 2703 436 4184 1625 13840 3037 2078 608 427 ...
 $ Age_Adjusted_Death_Rate: num  49.4 53.8 63.7 56.2 51.8 33.2 53.6 53.2 61.9 61 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cdc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year       Cause_Name           State               Deaths       
 Min.   :1999   Length:10868       Length:10868       Min.   :     21  
 1st Qu.:2003   Class :character   Class :character   1st Qu.:    612  
 Median :2008   Mode  :character   Mode  :character   Median :   1718  
 Mean   :2008                                         Mean   :  15460  
 3rd Qu.:2013                                         3rd Qu.:   5756  
 Max.   :2017                                         Max.   :2813503  
 Age_Adjusted_Death_Rate
 Min.   :   2.6         
 1st Qu.:  19.2         
 Median :  35.9         
 Mean   : 127.6         
 3rd Qu.: 151.7         
 Max.   :1087.3         </code></pre>
</div>
</div>
<p>There are no weird symbols or missing values in the raw data. Because the variables for “X113 cause name” and “cause name” provide the same information, the variable for “X113 cause name” is removed from the processed data. The new dataset has 10,868 observations and five variables: year, cause name, state, deaths, and age-adjusted death rate.</p>
</section>
<section id="part-3---exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="part-3---exploring-the-data">Part 3 - Exploring the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "Year"</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Year
1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
 572  572  572  572  572  572  572  572  572  572  572  572  572  572  572  572 
2015 2016 2017 
 572  572  572 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(Year))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Year
      1999       2000       2001       2002       2003       2004       2005 
0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 
      2006       2007       2008       2009       2010       2011       2012 
0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 
      2013       2014       2015       2016       2017 
0.05263158 0.05263158 0.05263158 0.05263158 0.05263158 </code></pre>
</div>
</div>
<p>19 years (1999-2017) are represented in the categorical variable “Year”, each with 572 observations (5.3%).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "Cause_Name"</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Cause_Name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cause_Name
             All causes     Alzheimer's disease                  Cancer 
                    988                     988                     988 
                   CLRD                Diabetes           Heart disease 
                    988                     988                     988 
Influenza and pneumonia          Kidney disease                  Stroke 
                    988                     988                     988 
                Suicide  Unintentional injuries 
                    988                     988 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(Cause_Name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cause_Name
             All causes     Alzheimer's disease                  Cancer 
             0.09090909              0.09090909              0.09090909 
                   CLRD                Diabetes           Heart disease 
             0.09090909              0.09090909              0.09090909 
Influenza and pneumonia          Kidney disease                  Stroke 
             0.09090909              0.09090909              0.09090909 
                Suicide  Unintentional injuries 
             0.09090909              0.09090909 </code></pre>
</div>
</div>
<p>11 cause categories are represented in the categorical variable “Cause_Name”, each with 988 observations (9.1%). The cause categories are “All causes”, “Alzheimer’s disease”, “Cancer”, “CLRD”, “Diabetes”, “Heart disease”, “Influenza and pneumonia”, “Kidney disease”, “Stroke”, “Suicide”, and “Unintentional injuries”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "State"</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(State)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>State
             Alabama               Alaska              Arizona 
                 209                  209                  209 
            Arkansas           California             Colorado 
                 209                  209                  209 
         Connecticut             Delaware District of Columbia 
                 209                  209                  209 
             Florida              Georgia               Hawaii 
                 209                  209                  209 
               Idaho             Illinois              Indiana 
                 209                  209                  209 
                Iowa               Kansas             Kentucky 
                 209                  209                  209 
           Louisiana                Maine             Maryland 
                 209                  209                  209 
       Massachusetts             Michigan            Minnesota 
                 209                  209                  209 
         Mississippi             Missouri              Montana 
                 209                  209                  209 
            Nebraska               Nevada        New Hampshire 
                 209                  209                  209 
          New Jersey           New Mexico             New York 
                 209                  209                  209 
      North Carolina         North Dakota                 Ohio 
                 209                  209                  209 
            Oklahoma               Oregon         Pennsylvania 
                 209                  209                  209 
        Rhode Island       South Carolina         South Dakota 
                 209                  209                  209 
           Tennessee                Texas        United States 
                 209                  209                  209 
                Utah              Vermont             Virginia 
                 209                  209                  209 
          Washington        West Virginia            Wisconsin 
                 209                  209                  209 
             Wyoming 
                 209 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(State))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>State
             Alabama               Alaska              Arizona 
          0.01923077           0.01923077           0.01923077 
            Arkansas           California             Colorado 
          0.01923077           0.01923077           0.01923077 
         Connecticut             Delaware District of Columbia 
          0.01923077           0.01923077           0.01923077 
             Florida              Georgia               Hawaii 
          0.01923077           0.01923077           0.01923077 
               Idaho             Illinois              Indiana 
          0.01923077           0.01923077           0.01923077 
                Iowa               Kansas             Kentucky 
          0.01923077           0.01923077           0.01923077 
           Louisiana                Maine             Maryland 
          0.01923077           0.01923077           0.01923077 
       Massachusetts             Michigan            Minnesota 
          0.01923077           0.01923077           0.01923077 
         Mississippi             Missouri              Montana 
          0.01923077           0.01923077           0.01923077 
            Nebraska               Nevada        New Hampshire 
          0.01923077           0.01923077           0.01923077 
          New Jersey           New Mexico             New York 
          0.01923077           0.01923077           0.01923077 
      North Carolina         North Dakota                 Ohio 
          0.01923077           0.01923077           0.01923077 
            Oklahoma               Oregon         Pennsylvania 
          0.01923077           0.01923077           0.01923077 
        Rhode Island       South Carolina         South Dakota 
          0.01923077           0.01923077           0.01923077 
           Tennessee                Texas        United States 
          0.01923077           0.01923077           0.01923077 
                Utah              Vermont             Virginia 
          0.01923077           0.01923077           0.01923077 
          Washington        West Virginia            Wisconsin 
          0.01923077           0.01923077           0.01923077 
             Wyoming 
          0.01923077 </code></pre>
</div>
</div>
<p>52 states/districts are represented in the categorical variable “State”, each with 209 observations (1.9%). All 50 states are represented, as well as “District of Columbia” and “United States”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary statistics and histogram for the continuous variable "Deaths"</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     21     612    1718   15460    5756 2813503 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(Deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 112876</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdc, <span class="fu">aes</span>(<span class="at">x =</span> Deaths)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density), <span class="at">fill =</span> <span class="st">"red"</span>), <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span> <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">with</span>(cdc, <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Deaths), <span class="at">sd =</span> <span class="fu">sd</span>(Deaths)))) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="st">"Number of Deaths"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Histogram with Normal Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram for the continuous variable “Deaths” does not show an approximately normal distribution. The mean is 15,460 deaths, and the standard deviation is 112,876 deaths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary statistics and histogram for the continuous variable "Age_Adjusted_Death_Rate"</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Age_Adjusted_Death_Rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    2.6    19.2    35.9   127.6   151.7  1087.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(Age_Adjusted_Death_Rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 223.6398</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cdc, <span class="fu">aes</span>(<span class="at">x =</span> Age_Adjusted_Death_Rate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density), <span class="at">fill =</span> <span class="st">"red"</span>), <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span> <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">with</span>(cdc, <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Age_Adjusted_Death_Rate), <span class="at">sd =</span> <span class="fu">sd</span>(Age_Adjusted_Death_Rate)))) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="st">"Age-Adjusted Death Rate"</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"Histogram with Normal Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram for the continuous variable “Age_Adjusted_Death_Rate” does not show an approximately normal distribution. The mean is 127.6 deaths per 100,000 population, and the standard deviation is 223.6 deaths per 100,000 population.</p>
<hr>
</section>
<section id="this-section-contributed-by-liza-hall" class="level1">
<h1>This section contributed by Liza Hall</h1>
</section>
<section id="section" class="level1">
<h1></h1>
<section id="synthetic-data" class="level2">
<h2 class="anchored" data-anchor-id="synthetic-data">Synthetic Data</h2>
<p>To create a synthetic dataset based on the previous analysis, I provided a LLM AI tool (ChatGPT) the following information, so that it could generate some code to generate data based off of the numbers provided.</p>
<table class="table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 64%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>‘Year’</th>
<th>‘Age_Adjusted_Death_Rate’</th>
<th>’Cause_Name”</th>
<th>‘State’</th>
<th>‘Deaths’</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>Min. : 1999</p>
<p>1st Qu. : 2003</p>
<p>Median : 2008</p>
<p>Mean : 2008</p>
<p>3rd Qu. : 2013</p>
<p>Max. : 2017</p></td>
<td><p>Min. &nbsp; : &nbsp; 2.6</p>
<p>1st Qu.:&nbsp; 19.2</p>
<p>Median :&nbsp; 35.9</p>
<p>Mean &nbsp; : 127.6</p>
<p>3rd Qu.: 151.7</p>
<p>Max. &nbsp; :1087.3</p></td>
<td><p>Length:10868</p>
<p>Class :character</p>
<p>Mode :character</p>
<p>Cause categories:</p>
<p>All causes, Alzheimer’s disease, Cancer, CLRD, Diabetes, Heart disease, Influenza and pneumonia, Kidney disease, Stroke, Suicide, Unintentional injuries</p></td>
<td><p>Length:10868</p>
<p>Class :character</p>
<p>Mode :character</p></td>
<td><p>Min. : 21</p>
<p>1st Qu. : 612</p>
<p>Median : 1718</p>
<p>Mean : 15460</p>
<p>3rd Qu. : 5756</p>
<p>Max. : 28135503</p></td>
</tr>
</tbody>
</table>
<p>Based on what the AI generated I was able to edit and adjust as needed to get the following code:</p>
<p>Loading the necessary libraries and setting a seed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">042</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Generating numerical values for synthetic dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the number of observations</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>num_obs <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data for 'Year'</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>year <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1999</span><span class="sc">:</span><span class="dv">2017</span>, num_obs, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data for 'age_adjusted_death_rate'</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>age_adjusted_death_rate <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(num_obs, <span class="at">mean =</span> <span class="fl">127.6</span>, <span class="at">sd =</span> <span class="dv">150</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure no negative values for death rates</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>age_adjusted_death_rate <span class="ot">&lt;-</span> <span class="fu">pmax</span>(age_adjusted_death_rate, <span class="dv">0</span>)</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data for 'Deaths'</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>deaths <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(num_obs, <span class="at">mean =</span> <span class="dv">15460</span>, <span class="at">sd =</span> <span class="dv">10000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Generating text values for synthetic dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data for 'Cause_Name'</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>cause_name <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"All causes"</span>, <span class="st">"Alzheimer's disease"</span>, <span class="st">"Cancer"</span>, <span class="st">"CLRD"</span>, </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Diabetes"</span>, <span class="st">"Heart disease"</span>, <span class="st">"Influenza and pneumonia"</span>, </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Kidney disease"</span>, <span class="st">"Stroke"</span>, <span class="st">"Suicide"</span>, <span class="st">"Unintentional injuries"</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                     num_obs, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate synthetic data for 'State'</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>states <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Alabama"</span>, <span class="st">"Alaska"</span>, <span class="st">"Arizona"</span>, <span class="st">"Arkansas"</span>, <span class="st">"California"</span>, <span class="st">"Colorado"</span>, </span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Connecticut"</span>, <span class="st">"Delaware"</span>, <span class="st">"Florida"</span>, <span class="st">"Georgia"</span>, <span class="st">"Hawaii"</span>, <span class="st">"Idaho"</span>, </span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Illinois"</span>, <span class="st">"Indiana"</span>, <span class="st">"Iowa"</span>, <span class="st">"Kansas"</span>, <span class="st">"Kentucky"</span>, <span class="st">"Louisiana"</span>, </span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Maine"</span>, <span class="st">"Maryland"</span>, <span class="st">"Massachusetts"</span>, <span class="st">"Michigan"</span>, <span class="st">"Minnesota"</span>, </span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Mississippi"</span>, <span class="st">"Missouri"</span>, <span class="st">"Montana"</span>, <span class="st">"Nebraska"</span>, <span class="st">"Nevada"</span>, </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">"New Hampshire"</span>, <span class="st">"New Jersey"</span>, <span class="st">"New Mexico"</span>, <span class="st">"New York"</span>, </span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>            <span class="st">"North Carolina"</span>, <span class="st">"North Dakota"</span>, <span class="st">"Ohio"</span>, <span class="st">"Oklahoma"</span>, <span class="st">"Oregon"</span>, </span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Pennsylvania"</span>, <span class="st">"Rhode Island"</span>, <span class="st">"South Carolina"</span>, <span class="st">"South Dakota"</span>, </span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Tennessee"</span>, <span class="st">"Texas"</span>, <span class="st">"Utah"</span>, <span class="st">"Vermont"</span>, <span class="st">"Virginia"</span>, <span class="st">"Washington"</span>, </span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"West Virginia"</span>, <span class="st">"Wisconsin"</span>, <span class="st">"Wyoming"</span>)</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a>state <span class="ot">&lt;-</span> <span class="fu">sample</span>(states, num_obs, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, putting those values into the dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>synthetic_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Year =</span> year,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Age_Adjusted_Death_Rate =</span> age_adjusted_death_rate,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Cause_Name =</span> cause_name,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">State =</span> state,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">Deaths =</span> deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analyzing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-the-data">Analyzing the Data</h2>
<p>Summary of synthetic dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display summary of synthetic data</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(synthetic_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Year      Age_Adjusted_Death_Rate  Cause_Name           State          
 Min.   :1999   Min.   :  0.00          Length:10000       Length:10000      
 1st Qu.:2003   1st Qu.: 25.24          Class :character   Class :character  
 Median :2008   Median :127.86          Mode  :character   Mode  :character  
 Mean   :2008   Mean   :143.95                                               
 3rd Qu.:2013   3rd Qu.:228.17                                               
 Max.   :2017   Max.   :776.81                                               
     Deaths      
 Min.   :-21699  
 1st Qu.:  8614  
 Median : 15666  
 Mean   : 15611  
 3rd Qu.: 22600  
 Max.   : 56124  </code></pre>
</div>
</div>
<p>Summary for the variable “year”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "year"</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>year
1999 2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 
 528  538  512  517  544  509  512  504  497  607  534  550  540  516  495  504 
2015 2016 2017 
 562  510  521 </code></pre>
</div>
</div>
<p>Summary for the variable “cause_name”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "cause_name"</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cause_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>cause_name
             All causes     Alzheimer's disease                  Cancer 
                    954                     905                     927 
                   CLRD                Diabetes           Heart disease 
                    921                     886                     873 
Influenza and pneumonia          Kidney disease                  Stroke 
                    950                     887                     931 
                Suicide  Unintentional injuries 
                    875                     891 </code></pre>
</div>
</div>
<p>Summary for the variable “state”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary tables for the categorical variable "state"</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>state
       Alabama         Alaska        Arizona       Arkansas     California 
           220            196            197            207            189 
      Colorado    Connecticut       Delaware        Florida        Georgia 
           216            214            196            197            170 
        Hawaii          Idaho       Illinois        Indiana           Iowa 
           199            210            175            195            196 
        Kansas       Kentucky      Louisiana          Maine       Maryland 
           200            206            210            209            217 
 Massachusetts       Michigan      Minnesota    Mississippi       Missouri 
           171            251            193            218            192 
       Montana       Nebraska         Nevada  New Hampshire     New Jersey 
           242            187            182            201            196 
    New Mexico       New York North Carolina   North Dakota           Ohio 
           222            203            197            202            192 
      Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina 
           171            209            195            183            178 
  South Dakota      Tennessee          Texas           Utah        Vermont 
           226            217            198            174            195 
      Virginia     Washington  West Virginia      Wisconsin        Wyoming 
           180            186            200            213            207 </code></pre>
</div>
</div>
<p>Summary statistics and histogram for “death”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary statistics and histogram for the continuous variable "Deaths"</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -21699    8614   15666   15611   22600   56124 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(deaths)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10127.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> deaths)) <span class="sc">+</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density), </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"red"</span>), <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span> </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">with</span>(synthetic_data, </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(deaths), <span class="at">sd =</span> <span class="fu">sd</span>(deaths)))) <span class="sc">+</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">"Number of Deaths"</span>) <span class="sc">+</span> </span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Histogram with Normal Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram displays a strong normal distribution. Which varies from what was found in the original dataset. I suspect that this is due to the randomized nature of the synthetic data, vs the real data which contains real-world biases and trends.</p>
<hr>
<p>Summary statistics and histogram for “age_adjusted_death_rate”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Summary statistics and histogram for the continuous variable "age_adjusted_death_rate"</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(age_adjusted_death_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   25.24  127.86  143.95  228.17  776.81 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(age_adjusted_death_rate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125.881</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(synthetic_data, <span class="fu">aes</span>(<span class="at">x =</span> age_adjusted_death_rate)) <span class="sc">+</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density),</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fill =</span> <span class="st">"red"</span>), <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span> </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dnorm, <span class="at">args =</span> <span class="fu">with</span>(synthetic_data, </span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">mean =</span> <span class="fu">mean</span>(age_adjusted_death_rate),</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(age_adjusted_death_rate)))) <span class="sc">+</span> </span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">"Age-Adjusted Death Rate"</span>) <span class="sc">+</span> </span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Histogram with Normal Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cdcdata-exercise_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This histogram is closer in appearance to the one generated from the original dataset. It does not follow an approximately normal distribution, the mean is 143.95 and the standard deviation is 125.881 which while not exactly the same, is in the same sort of range as the original dataset.</p>
</section>
<section id="final-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="final-thoughts">Final thoughts</h2>
<p>Overall I noticed that the synthetic dataset had more variation in values than the original. As stated previously I suspect that this is due to the random nature of the data generation within the synthetic dataset. Despite being based on statistics pulled from analysis of the original data, the syntehtic dataset does not have the nuances or biases of the original data.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>